# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cronix < Formula
  desc "Cron jobs as code — reconcile app-declared schedules against the host scheduler"
  homepage "https://github.com/awbx/cronix"
  version "0.7.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/awbx/cronix/releases/download/v0.7.2/cronix_0.7.2_darwin_amd64.tar.gz"
      sha256 "f11e1640d6514f2a43300d94c56cdc60202fead1ae56a75a0e8db5203bbd9be0"

      define_method(:install) do
        bin.install "cronix"
        generate_completions_from_executable(bin/"cronix", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/awbx/cronix/releases/download/v0.7.2/cronix_0.7.2_darwin_arm64.tar.gz"
      sha256 "cab7b7b07eac10b6b265e199afe344b50fd7e939236d3db2aa7821ae9c6d4251"

      define_method(:install) do
        bin.install "cronix"
        generate_completions_from_executable(bin/"cronix", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/awbx/cronix/releases/download/v0.7.2/cronix_0.7.2_linux_amd64.tar.gz"
      sha256 "413c31ae295e92022db2c12bce919ceb015f1c88a443ad40ac8879be0c46dd11"
      define_method(:install) do
        bin.install "cronix"
        generate_completions_from_executable(bin/"cronix", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/awbx/cronix/releases/download/v0.7.2/cronix_0.7.2_linux_arm64.tar.gz"
      sha256 "b110f90f14384ac3b1ebe18387c40c6936c0af7ef252f94fc4ff0be19d11eaa5"
      define_method(:install) do
        bin.install "cronix"
        generate_completions_from_executable(bin/"cronix", "completion")
      end
    end
  end

  test do
    system "#{bin}/cronix", "version"
  end
end
