# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cronix < Formula
  desc "Cron jobs as code — reconcile app-declared schedules against the host scheduler"
  homepage "https://github.com/awbx/cronix"
  version "0.10.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/awbx/cronix/releases/download/v0.10.0/cronix_0.10.0_darwin_amd64.tar.gz"
      sha256 "f2e86a0f6bb060677ae24bc79d4873cfee536a66b2a7a07fa38fd04716633f8b"

      define_method(:install) do
        bin.install "cronix"
        generate_completions_from_executable(bin/"cronix", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/awbx/cronix/releases/download/v0.10.0/cronix_0.10.0_darwin_arm64.tar.gz"
      sha256 "db4fb35f554bda830cc00ecb6e966a4327413a4c62c9c2c760c52d2a45bbc91c"

      define_method(:install) do
        bin.install "cronix"
        generate_completions_from_executable(bin/"cronix", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/awbx/cronix/releases/download/v0.10.0/cronix_0.10.0_linux_amd64.tar.gz"
      sha256 "89bccad40eed71db08269ef179c5e76edc80ac1789dd0dd7d1ce1f6e7a539594"
      define_method(:install) do
        bin.install "cronix"
        generate_completions_from_executable(bin/"cronix", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/awbx/cronix/releases/download/v0.10.0/cronix_0.10.0_linux_arm64.tar.gz"
      sha256 "f680e71f2604a7c5a52c1808c1b8c41bee62ec95bd8e7a14b063926092922916"
      define_method(:install) do
        bin.install "cronix"
        generate_completions_from_executable(bin/"cronix", "completion")
      end
    end
  end

  test do
    system "#{bin}/cronix", "version"
  end
end
